server.port=8080

sptring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/blog
spring.datasource.username=root
spring.datasource.password=root

# Важно! Эта настройка автоматически создаст таблицы
spring.jpa.hibernate.ddl-auto=update

# Показывать SQL запросы для отладки
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Диалект для MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect