server.port=8080

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/blog
spring.datasource.username=root
spring.datasource.password=root

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JWT Settings
jwt.secret=66546A555E5A7234753778214123222A472D4B614E645262356B587032733576
jwt.access_token_duration_minute=5
jwt.access_token_duration_second=300
jwt.refresh_token_duration_day=7
jwt.refresh_token_duration_second=604800
jwt.access_cookie_name=access_token
jwt.refresh_cookie_name=refresh_token
# Путь для сохранения фото
upload.path=C:/Users/Булат/Desktop/blog/uploads/
# Увеличиваем размер полей
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.datasource.url=jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
server.address=0.0.0.0